"""Migration message

Revision ID: 13557238020e
Revises: 6305dd4476ec
Create Date: 2026-04-24 15:45:58.560527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13557238020e'
down_revision: Union[str, Sequence[str], None] = '6305dd4476ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('bills', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.add_column('bills', sa.Column('bill_pdf_url', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'bills', ['transaction_id'])
    op.drop_constraint(op.f('transactions_transaction_id_key'), 'transactions', type_='unique')
    op.drop_column('transactions', 'bill_pdf_url')
    op.drop_column('transactions', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('bill_pdf_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('transactions_transaction_id_key'), 'transactions', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'bills', type_='unique')
    op.drop_column('bills', 'bill_pdf_url')
    op.drop_column('bills', 'transaction_id')
    op.drop_column('bills', 'payment_method')
    # ### end Alembic commands ###
