"""migrete

Revision ID: 19956247ddec
Revises: add_cascade_deletes
Create Date: 2026-04-16 12:34:24.236792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19956247ddec'
down_revision: Union[str, Sequence[str], None] = 'add_cascade_deletes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_room_types_id'), 'room_types', ['id'], unique=False)
    op.drop_constraint(op.f('hostels_owner_id_fkey'), 'hostels', type_='foreignkey')
    op.create_foreign_key(None, 'hostels', 'owners', ['owner_id'], ['id'])
    op.alter_column('rooms', 'room_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='NULL')
    op.drop_constraint(op.f('rooms_hostel_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'hostels', ['hostel_id'], ['id'])
    op.create_foreign_key(None, 'rooms', 'room_types', ['room_type'], ['id'])
    op.drop_constraint(op.f('tenant_payments_tenant_id_fkey'), 'tenant_payments', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_payments', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('tenants_hostel_id_fkey'), 'tenants', type_='foreignkey')
    op.drop_constraint(op.f('tenants_room_id_fkey'), 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'hostels', ['hostel_id'], ['id'])
    op.create_foreign_key(None, 'tenants', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_room_id_fkey'), 'tenants', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('tenants_hostel_id_fkey'), 'tenants', 'hostels', ['hostel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tenant_payments', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_payments_tenant_id_fkey'), 'tenant_payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_hostel_id_fkey'), 'rooms', 'hostels', ['hostel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rooms', 'room_type',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'hostels', type_='foreignkey')
    op.create_foreign_key(op.f('hostels_owner_id_fkey'), 'hostels', 'owners', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_room_types_id'), table_name='room_types')
    op.drop_table('room_types')
    # ### end Alembic commands ###
