"""Remove no_of_occupied_beds column from rooms table

Revision ID: 2faf7a6936ab
Revises: f35eae174e1b
Create Date: 2026-04-22 12:20:44.746016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2faf7a6936ab'
down_revision: Union[str, Sequence[str], None] = 'f35eae174e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'no_of_occupied_beds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('no_of_occupied_beds', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
