"""Migration message

Revision ID: 3158632a5e2c
Revises: 13557238020e
Create Date: 2026-04-27 16:08:36.037647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3158632a5e2c'
down_revision: Union[str, Sequence[str], None] = '13557238020e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_types', 'theme_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('theme_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
