"""migrete

Revision ID: 38ab08b90fd7
Revises: 6fed16a4c340
Create Date: 2026-04-15 12:15:13.922635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ab08b90fd7'
down_revision: Union[str, Sequence[str], None] = '6fed16a4c340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('security_deposit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'security_deposit')
    # ### end Alembic commands ###
