"""Migration message

Revision ID: 6305dd4476ec
Revises: cb1ca76649df
Create Date: 2026-04-24 13:12:02.691923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6305dd4476ec'
down_revision: Union[str, Sequence[str], None] = 'cb1ca76649df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('bill_pdf_url', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'bill_pdf_url')
    op.drop_column('transactions', 'transaction_id')
    # ### end Alembic commands ###
