"""Add theme_color field to hostels, rooms, and room_types

Revision ID: cb1ca76649df
Revises: 2faf7a6936ab
Create Date: 2026-04-22 15:50:03.609057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1ca76649df'
down_revision: Union[str, Sequence[str], None] = '2faf7a6936ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('theme_color', sa.String(length=7), nullable=True))
    op.add_column('room_types', sa.Column('theme_color', sa.String(length=7), nullable=True))
    op.add_column('rooms', sa.Column('theme_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'theme_color')
    op.drop_column('room_types', 'theme_color')
    op.drop_column('hostels', 'theme_color')
    # ### end Alembic commands ###
